module.exports = {
    SWITCH_TO_BIENS: 'SWITCH_TO_BIENS',
    FETCH_BIENS: 'FETCH_BIENS',
    SWITCH_TO_BATIMENTS: 'SWITCH_TO_BATIMENTS',
    FETCH_BATIMENTS: 'FETCH_BATIMENTS',
    SWITCH_TO_TYPE_LOGEMENTS: 'SWITCH_TO_TYPE_LOGEMENTS',
    FETCH_TYPE_LOGEMENTS: 'FETCH_TYPE_LOGEMENTS',    
    SWITCH_TO_LOGEMENTS: 'SWITCH_TO_LOGEMENTS',
    FETCH_LOGEMENTS: 'FETCH_LOGEMENTS',  
    SWITCH_TO_LOGEMENT_DETAIL: 'SWITCH_TO_LOGEMENT_DETAIL',  
    SWITCH_TO_DOSSIER_LOGEMENT: 'SWITCH_TO_DOSSIER_LOGEMENT',
    FETCH_LOGEMENT_DETAIL: 'FETCH_LOGEMENT_DETAIL',
    PASS_TYPE_LOGEMENT_PARAMS: 'PASS_TYPE_LOGEMENT_PARAMS',
    PASS_LOGEMENT_PARAMS: 'PASS_LOGEMENT_PARAMS',
    PASS_LOGEMENT_DETAIL_PARAMS: 'PASS_LOGEMENT_DETAIL_PARAMS',
    FETCH_CHARACTERISTIQUES_LOGEMENTS: 'FETCH_CHARACTERISTIQUES_LOGEMENTS',
    FETCH_BIENS_SUCCESS: 'FETCH_BIENS_SUCCESS',
    FETCH_BIENS_ERROR: 'FETCH_BIENS_ERROR'
} 