module.exports = {
    DISPLAY_TDB: 'DISPLAY_TDB',   
    DISPLAY_BIENS: 'DISPLAY_BIENS',   
    DISPLAY_LOCATAIRES: 'DISPLAY_LOCATAIRES',   
    DISPLAY_LOYERS: 'DISPLAY_LOYERS',   
    DISPLAY_CDB: 'DISPLAY_CDB',   
    DISPLAY_PENALITES: 'DISPLAY_PENALITES',   
    DISPLAY_INDEX: 'DISPLAY_INDEX',   
    DISPLAY_ETAT: 'DISPLAY_ETAT',   
    DISPLAY_DECONNEXION: 'DISPLAY_DECONNEXION',       
} 