module.exports = {
    SHOW_MENU: 'SHOW_MENU',
    HIDE_MENU: 'HIDE_MENU',
    SHOW_DOSSIER_HABITANT_DRAWER_MENU: 'SHOW_DOSSIER_HABITANT_DRAWER_MENU',
    HIDE_DOSSIER_HABITANT_DRAWER_MENU: 'HIDE_DOSSIER_HABITANT_DRAWER_MENU',
    IS_BIENS: 'IS_BIENS',
    IS_BATIMENTS: 'IS_BATIMENTS',
    IS_TYPE_LOGEMENTS: 'IS_TYPE_LOGEMENTS',
    IS_LOGEMENT: 'IS_LOGEMENT',
    IS_LOGEMENT_DETAIL: 'IS_LOGEMENT_DETAIL'
} 