module.exports = {
    USERNAME_CHANGE: 'USERNAME_CHANGE',
    PASSWORD_CHANGE: 'PASSWORD_CHANGE',
    PASSWORD_VISIBILITY_CHANGE: 'PASSWORD_VISIBILITY_CHANGE',
    ACCOUNT_TYPE_CHANGE: 'ACCOUNT_TYPE_CHANGE',
    IS_LOADING: 'IS_LOADING',
    SIGN_IN: 'SIGN_IN',
    SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
    SIGN_IN_ERROR: 'SIGN_IN_ERROR',
    
} 